name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests (Firefox)
        run: npx cypress run --browser firefox
